/** Declaration file generated by dts-gen */

export const DIE: {
    D10: number;
    D12: number;
    D20: number;
    D4: number;
    D6: number;
    D8: number;
};

export function roll(amount: any, die: any): any;

export namespace roll {
    const prototype: {
    };

}

